export const formatClient = (client) => {
  return {
    tipo_pessoa: client.type,
    data_nascimento: client.birth_date,
    cnpj_cpf: client.cpf,
    ie_identidade: client.ie_rg,
    razao: client.name,
    fantasia: client.fantasy_name,
    tipo_cliente_scm: client.client_type,
    id_tipo_cliente: client.subscriber_type,
    contribuinte_icms: client.icms_contributor || false,
    nacionalidade: client.nationality,
    ativo: client.active || true,
    sexo: client.sex,
    profissao: client.profession,
    tipo_assinante: client.subscriber_type,
    filial_id: client.branch || 0,
    cep: client.zip_code,
    endereco: client.street,
    numero: client.number,
    complemento: client.complement,
    bairro: client.neighborhood,
    cidade: client.city,
    referencia: client.reference,
    moradia: client.housing_type,
    telefone_celular: client.mobile,
    whatsapp: client.whatsapp,
    email: client.email,
    id_campanha: client.sales_channel,
    id_concorrente: client.competitor,
    id_perfil: client.profile,
    responsavel: client.responsible,
    id_conta: client.billing_address,
    cond_pagamento: client.payment_condition,
    id_vendedor: client.seller,
    nome_pai: client.father_name,
    nome_mae: client.mother_name,
  };
};
