const permissions = {
  "/painel": [],
  "/auditorias": [
    "view_any_tasks",
    "update_tasks",
    "view_any_reports",
    "report_generate",
    "define_rules",
    "view_tasks",
  ],
  "/empresas": [
    "view_companies",
    "view_any_companies",
    "create_companies",
    "update_companies",
    "delete_companies",
  ],
  "/papeis": [
    "view_roles",
    "view_any_roles",
    "create_roles",
    "update_roles",
    "delete_roles",
    "view_from_company",
  ],
  "/usuarios": [
    "view_users",
    "view_any_users",
    "create_users",
    "update_users",
    "delete_users",
    "assign_responsible_users",
    "unassign_responsible_users",
  ],
  "/clientes": [
    "view_clients",
    "view_any_clients",
    "create_clients",
    "update_clients",
    "delete_clients",
  ],
  "/clientes/criar": ["create_clients"],
  "/ordens-de-servico": [
    "view_any_work_orders",
    "view_work_orders",
    "update_work_orders",
    "create_work_orders",
    "delete_work_orders",
    "assign_work_orders",
    "be_assigned_work_orders",
  ],
  "/prioridades": ["define_rules"],
  "/permissoes": [],
  "/logs": ["view_any_logs"],
  "/regras": ["define_rules"],
  "/regras/criar": ["create_audit_rules"],
};

export const pagePermissions = (path) => permissions[path] ?? [];
